name:  run unit tests

on:
  push:
    branches: 
      'feature/*'
jobs:  
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name:  run unit test
        run:  mvn test 
      
